version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/examples/simple"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/examples/classification"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/examples/embedding"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/examples/graphql"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/examples/textgeneration"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
